export interface LaserParameterSource {
  id: string;
  name: string;
  logo?: string;
  verified?: boolean;
}

export interface LaserParameter {
  name: string;
  passes: number;
  speed: number;
  power: number;
  frequency: number;
  lineDistance: number | string;
  hatchAngle: string;
  hatchPattern: string;
  notes: string;
  source: LaserParameterSource;
}

// Define our sources
const sources: Record<string, LaserParameterSource> = {
  cloudray: {
    id: "cloudray",
    name: "Cloudray Official",
    verified: true
  },
  community: {
    id: "community",
    name: "MFM Community",
    verified: true
  }
};

export const laserParameters: LaserParameter[] = [
  {
    name: "Aluminum General",
    passes: 1,
    speed: 390,
    power: 100,
    frequency: 30,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  // Add a community version of the same settings with slight differences
  {
    name: "Aluminum General",
    passes: 1,
    speed: 400,
    power: 95,
    frequency: 30,
    lineDistance: 0.03,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Use denatured alcohol for cleaning after engraving",
    source: sources.community
  },
  {
    name: "Aluminum Deep",
    passes: 2,
    speed: 194,
    power: 100,
    frequency: 35,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "Aluminum Dark",
    passes: 1,
    speed: 583,
    power: 100,
    frequency: 45,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "Aluminum White",
    passes: 1,
    speed: 583,
    power: 15,
    lineDistance: 0.025,
    frequency: 45,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "Aluminum Cut",
    passes: 25,
    speed: 584,
    power: 100,
    frequency: 30,
    lineDistance: "None",
    hatchAngle: "None",
    hatchPattern: "None",
    notes: "Cut with 0.01mm Diameter and Distance",
    source: sources.cloudray
  },
  {
    name: "Aluminum Photos",
    passes: 1,
    speed: 250,
    power: 64,
    frequency: 45,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Standard",
    notes: "May need up to 2 passes for extra details. Photo DPI should be around 300-350",
    source: sources.cloudray
  },
  // Community alternative for photos
  {
    name: "Aluminum Photos",
    passes: 2,
    speed: 230,
    power: 70,
    frequency: 40,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Standard",
    notes: "For better details, pre-clean aluminum with acetone and use 2 passes",
    source: sources.community
  },
  {
    name: "Black Acrylic - White Raised Lettering",
    passes: 3,
    speed: 1000,
    power: 64,
    frequency: 35,
    lineDistance: 0.1,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Will bubble up if too much heat is used",
    source: sources.cloudray
  },
  {
    name: "Brass Black Deep",
    passes: 2,
    speed: 389,
    power: 100,
    frequency: 35,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Use a soft toothbrush with all purpose cleaner to clean the remaining debris. Clear Coat for extra shine",
    source: sources.cloudray
  },
  {
    name: "Brass General",
    passes: 1,
    speed: 389,
    power: 100,
    frequency: 50,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Use a soft toothbrush with all purpose cleaner to clean the remaining debris",
    source: sources.cloudray
  },
  {
    name: "Brass White",
    passes: 1,
    speed: 586,
    power: 100,
    frequency: 45,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "Brass Photo Details",
    passes: 1,
    speed: 97,
    power: 100,
    frequency: 35,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "Works best with brass general base pass",
    source: sources.cloudray
  },
  {
    name: "Black Ceramic Coatings - General",
    passes: 2,
    speed: 389,
    power: 100,
    frequency: 35,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Use a soft toothbrush with all purpose cleaner to clean the remaining debris",
    source: sources.cloudray
  },
  {
    name: "Plastic Facing General",
    passes: 1,
    speed: 389,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Remove Electric Plating to engrave base metal underneath",
    source: sources.cloudray
  },
  {
    name: "Glass Steel Second",
    passes: 1,
    speed: 389,
    power: 100,
    frequency: 20,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Snake",
    notes: "Place steel behind glass, focus steel to steel, place glass on top, reverse image and engrave",
    source: sources.cloudray
  },
  {
    name: "Glass Black (Ivory Paint)",
    passes: 1,
    speed: 20,
    power: 18,
    frequency: 80,
    lineDistance: 0.1,
    hatchAngle: "0°",
    hatchPattern: "Standard",
    notes: "Spray ivory paint on, let tack up then engrave. Use paint thiner to remove leftover paint",
    source: sources.cloudray
  },
  {
    name: "Glass White (paint) & (Enamel Paint)",
    passes: 1,
    speed: 19,
    power: 18,
    frequency: 80,
    lineDistance: 0.1,
    hatchAngle: "0°",
    hatchPattern: "Standard",
    notes: "Coat paint on, let tack up then engrave. Use paint thiner to remove leftover paint. (Black Opaque Tempera Paint can be bought on amazon)",
    source: sources.cloudray
  },
  {
    name: "Glass Engrave",
    passes: 1,
    speed: 98,
    power: 100,
    frequency: 37,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "May require multiple passes but take 1 min inbetween to cool down",
    source: sources.cloudray
  },
  {
    name: "Gold Yellow 10-14K Base",
    passes: 1,
    speed: 600,
    power: 92,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Yellow 10-14K Bright",
    passes: 1,
    speed: 978,
    power: 100,
    frequency: 190,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Yellow 10-14K Cleanup",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Yellow 10-14K Details",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 25,
    lineDistance: 0.001,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Yellow 10-14K Medium",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 200,
    lineDistance: 0.001,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Base",
    passes: 1,
    speed: 500,
    power: 92,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Cleanup",
    passes: 1,
    speed: 978,
    power: 56,
    frequency: 45,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Gold Anneal",
    passes: 1,
    speed: 750,
    power: 100,
    frequency: 190,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Black",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 25,
    lineDistance: 0.001,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Gold Anneal",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 200,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Rose 10-14K Base",
    passes: 1,
    speed: 750,
    power: 92,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Rose 10-14K Cleanup",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 45,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Rose 10-14K Bright",
    passes: 1,
    speed: 978,
    power: 100,
    frequency: 190,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Rose 10-14K Medium",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 200,
    lineDistance: 0.001,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Rose 10-14K Black",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 25,
    lineDistance: 0.001,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Y/R 10-14K Photo Base",
    passes: 1,
    speed: 750,
    power: 92,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Y/R 10-14K Photo Cleanup",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 45,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold Y/R 10-14K Photo Details",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Photo Base",
    passes: 1,
    speed: 500,
    power: 92,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Photo Dark",
    passes: 1,
    speed: 978,
    power: 100,
    frequency: 190,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Gold White 10-14K Photo Details",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Granite (Black) - Gray Engrave",
    passes: 1,
    speed: 390,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Run as many times as you want for added depth, gets less efficient over time though",
    source: sources.cloudray
  },
  {
    name: "Leather General",
    passes: 1,
    speed: 500,
    power: 25,
    frequency: 200,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Mainly used for Leatherette",
    source: sources.cloudray
  },
  {
    name: "Leather Dark",
    passes: 1,
    speed: 500,
    power: 35,
    frequency: 200,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Used for larger text or designs",
    source: sources.cloudray
  },
  {
    name: "Leather Bright",
    passes: 1,
    speed: 500,
    power: 100,
    frequency: 200,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "If you experience excessive burning. 1= 2 Pass Resistant. 2= 2 Pass Gentle",
    source: sources.cloudray
  },
  {
    name: "Leather Resistant",
    passes: 1,
    speed: 500,
    power: 92,
    frequency: 200,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "For use with the rotary tool on curves, same configurations as above. .38mm focus",
    source: sources.cloudray
  },
  {
    name: "Powder Coat - 1 Layer Removal",
    passes: 1,
    speed: 391,
    power: 100,
    frequency: 150,
    lineDistance: 0.02,
    hatchAngle: "90°",
    hatchPattern: "Standard",
    notes: "For use with the rotary tool, will require alcohol and magic eraser to remove residue. +4mm focus",
    source: sources.cloudray
  },
  {
    name: "Powder Coat - Sharp",
    passes: 1,
    speed: 294,
    power: 100,
    frequency: 80,
    lineDistance: 0.02,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "No base pass. Engrave directly into the coating. Will be darker than the previous area, mark as needed.",
    source: sources.cloudray
  },
  {
    name: "Powder Coat - Photo Removal",
    passes: 1,
    speed: 196,
    power: 100,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Silver - Stone General Engrave",
    passes: 1,
    speed: 972,
    power: 100,
    frequency: 30,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Silver General Engrave",
    passes: 1,
    speed: 500,
    power: 79,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Yellow color is natural fiber layer result, your settings are correct.",
    source: sources.cloudray
  },
  {
    name: "Silver Dark Deep",
    passes: 1,
    speed: 117,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Only works on solid silver, silver plating is too thin to stand up to this mark.",
    source: sources.cloudray
  },
  {
    name: "Silver Photo Base (Step 1)",
    passes: 1,
    speed: 98,
    power: 56,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "Use smooth surface base plate.",
    source: sources.cloudray
  },
  {
    name: "Silver Photo Base (Step 1)",
    passes: 1,
    speed: 98,
    power: 100,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "Use for photo reactive background FIRST",
    source: sources.cloudray
  },
  {
    name: "Silver Photo White (Step 2)",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 50,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "Use for photo reactive background SECOND",
    source: sources.cloudray
  },
  {
    name: "Silver Photo Details (Step 3)",
    passes: 1,
    speed: 98,
    power: 100,
    frequency: 25,
    lineDistance: "Photo",
    hatchAngle: "Photo",
    hatchPattern: "Photo",
    notes: "Run your actual photo on top of your base with this pass. Make sure to check pixel power and enable mark low.",
    source: sources.cloudray
  },
  {
    name: "Silver - Base Gray",
    passes: 1,
    speed: 250,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Run as many times as needed for depth",
    source: sources.cloudray
  },
  {
    name: "Silver Shine Black",
    passes: 1,
    speed: 750,
    power: 56,
    frequency: 45,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Anodized silver. Use hairspray & paint to get to desired oxidized color.",
    source: sources.cloudray
  },
  {
    name: "Steel - General Engrave",
    passes: 1,
    speed: 389,
    power: 100,
    frequency: 30,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Apply 3-in-1 Oil. Brush generously. (Optionally clean with degreaser)",
    source: sources.cloudray
  },
  {
    name: "Steel - Deep Engrave",
    passes: 1,
    speed: 389,
    power: 100,
    frequency: 37,
    lineDistance: 0.01,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Finish with Steel General Cleaning Pass. Black Oxide or Steel White finish.",
    source: sources.cloudray
  },
  {
    name: "Steel - Cleaning Pass",
    passes: 1,
    speed: 1000,
    power: 77,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Used to help burn carbon out. Helps set up material for Annealing",
    source: sources.cloudray
  },
  {
    name: "Steel - Black Anneal",
    passes: 1,
    speed: 750,
    power: 69,
    frequency: 150,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Helps protect the steel by heating it after engraving, has a shiny blue rainbow effect. Oil when complete",
    source: sources.cloudray
  },
  {
    name: "Steel - White Anneal",
    passes: 1,
    speed: 750,
    power: 64,
    frequency: 45,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "Steel - Rich Black Anneal",
    passes: 1,
    speed: 50,
    power: 79,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Defocus laser 1-3mm AWAY from material for best results",
    source: sources.cloudray
  },
  {
    name: "Tin General Engrave",
    passes: 1,
    speed: 361,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "Titanium General Engrave",
    passes: 1,
    speed: 146,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "Titanium Gold Anneal",
    passes: 1,
    speed: 330,
    power: 69,
    frequency: 190,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Helps protect the steel by heating it after engraving, turns titanium GOLD. Oil when complete.",
    source: sources.cloudray
  },
  {
    name: "Titanium Rich Black Anneal",
    passes: 1,
    speed: 97,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Defocus laser 1-3mm AWAY from material for best results",
    source: sources.cloudray
  },
  {
    name: "MDF - Black Tall",
    passes: 1,
    speed: 500,
    power: 100,
    frequency: 50,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "MDF - Cut (4mm)",
    passes: 18,
    speed: 98,
    power: 100,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Zinc General",
    passes: 5,
    speed: 194,
    power: 100,
    frequency: 50,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Zinc Coins - Deep Engrave Dark",
    passes: 5,
    speed: 194,
    power: 100,
    frequency: 50,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Zinc Coins - White Anneal",
    passes: 1,
    speed: 2000,
    power: 77,
    frequency: 75,
    lineDistance: 0.1,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "Clean with cloth after finishing",
    source: sources.cloudray
  },
  {
    name: "ABS - General",
    passes: 1,
    speed: 3000,
    power: 46,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "ABS - Black",
    passes: 1,
    speed: 3000,
    power: 92,
    frequency: 200,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "ABS - White",
    passes: 1,
    speed: 1500,
    power: 46,
    frequency: 90,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Black Delerin - Tan",
    passes: 1,
    speed: 1500,
    power: 25,
    frequency: 20,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Golf Ball - Mark",
    passes: 1,
    speed: 1750,
    power: 38,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  },
  {
    name: "Nylon - General",
    passes: 1,
    speed: 1000,
    power: 41,
    frequency: 25,
    lineDistance: 0.025,
    hatchAngle: "45°",
    hatchPattern: "Standard",
    notes: "",
    source: sources.cloudray
  }
]; 